MiaoliGym/Models/GymRecord.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace MiaoliGym.Models
{
    [DisplayName("館場借用紀錄")]
    public class GymRecord
    {
        [Key]
        public int Id { get; set; }
   
        [Required]
        public virtual Gym Gym { get; set; }

        [DisplayName("借用單位")]
        [Required(ErrorMessage="請輸入借用單位")]
        [MaxLength(30,ErrorMessage="借用單位名稱不得超過30字")]
        public string LendUnit { get; set; }

        [DisplayName("借用時間-起")]
        [DataType(DataType.DateTime)]
        [Required(ErrorMessage="請輸入借用時間-起")]
        public DateTime LendDateStart { get; set; }

        // UNDONE: DateCompareValidation
        [DisplayName("借用時間-迄")]
        [DataType(DataType.DateTime)]
        [Required(ErrorMessage="請輸入借用時間-迄")]
        [DateCompareValidation(DateCompareValidationAttribute.CompareType.GreatherThenOrEqualTo, "結束日期必須要大於起始日期", compareWith: "LendDateStart")]
        public DateTime LendDateEnd { get; set; }

        [DisplayName("活動名稱")]
        [Required(ErrorMessage="請輸入活動名稱或借用事由")]
        [Description("借用場地的相關活動或事由")]
        public string Event { get; set; }

        [DisplayName("聯絡人")]
        [MaxLength(50,ErrorMessage="姓名不得大於50個字元")]
        public string Contacter { get; set; }

        [Required(ErrorMessage="請輸入聯絡電話")]
        [DisplayName("聯絡電話")]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(25, ErrorMessage="電話長度不可超過25字元")]
        public string ContactPhone { get; set; }

        [DisplayName("核准文號")]
        [Required(ErrorMessage="請輸入核准文號")]
        public string ApprovalNo { get; set; }

        [DisplayName("建立時間")]
        [Required]
        public DateTime CreateOn { get; set; }

        [DisplayName("更新時間")]
        public DateTime? LastUpdateOn { get; set; }

        [Required]
        public string LastEditor { get; set; }

        [Required]
        public bool Deleted { get; set; }


        //----------------------------------------------------------------------------------------

        public virtual ICollection<PayItem> PayItems { get; set; }
        public virtual ICollection<FreeItem> FreeItems { get; set; }
        public virtual ICollection<SendbackItem> SendbackItems { get; set; }

    }
}

MiaoliGym/Controllers/GymRecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiaoliGym.Models;
using PagedList;

namespace MiaoliGym.Controllers
{
    public class GymRecordController : Controller
    {
        private MiaoliContext db = new MiaoliContext();
        private List<Gym> gyms;
        private List<GymRecord> gymRecords;
        private List<PayItem> payItems;
        private List<FreeItem> freeItems;
        private List<SendbackItem> sendbackItems;

        public GymRecordController()
        {
            #region Dummy Data
            gyms = new List<Gym>(){ 
                new Gym{ Id = 1, Name="巨蛋體育館", Description="N/A", CreateOn=DateTime.Now},
                new Gym{ Id = 2, Name="縣立田徑場", Description="N/A", CreateOn=DateTime.Now},
                new Gym{ Id = 3, Name="縣立網球場", Description="N/A", CreateOn=DateTime.Now},
                new Gym{ Id = 4, Name="代管棒壘場-大倫", Description="N/A", CreateOn=DateTime.Now},
                new Gym{ Id = 5, Name="代管棒壘場-後龍高灘地", Description="N/A", CreateOn=DateTime.Now},
                new Gym{ Id = 6, Name="代管棒壘場-照南", Description="N/A", CreateOn=DateTime.Now}
            };

           

            gymRecords = new List<GymRecord>(){
                new GymRecord{ Id=1, ApprovalNo="NO-98765432101", Contacter="AndyYou", ContactPhone="0911911911", CreateOn=DateTime.Now, Deleted=false, Event="巨星齊聚苗栗縣元宵節活動", Gym = gyms.Find(x => x.Id == 1), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊股份有限公司台灣分公司", FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>() },
                new GymRecord{ Id=2, ApprovalNo="NO-98765432102", Contacter="Calvert", ContactPhone="0922922922", CreateOn=DateTime.Now, Deleted=false, Event="春節晚會", Gym =  gyms.Find(x => x.Id == 2), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊" , FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>() },
                new GymRecord{ Id=3, ApprovalNo="NO-98765432103", Contacter="AndyYou", ContactPhone="0911911911", CreateOn=DateTime.Now, Deleted=false, Event="霹靂好玩的活動-1", Gym = gyms.Find(x => x.Id == 3), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊", FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>()  },
                new GymRecord{ Id=4, ApprovalNo="NO-98765432105", Contacter="Calvert", ContactPhone="0922922922", CreateOn=DateTime.Now, Deleted=false, Event="霹靂好玩的活動-2", Gym =  gyms.Find(x => x.Id == 4), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊", FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>()  },
                new GymRecord{ Id=5, ApprovalNo="NO-98765432101", Contacter="AndyYou", ContactPhone="0911911911", CreateOn=DateTime.Now, Deleted=false, Event="霹靂好玩的活動-3", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊" , FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>() },
                new GymRecord{ Id=6, ApprovalNo="NO-98765432102", Contacter="Calvert", ContactPhone="0922922922", CreateOn=DateTime.Now, Deleted=false, Event="春節晚會", Gym =  gyms.Find(x => x.Id == 1), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊" , FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>() },
                new GymRecord{ Id=7, ApprovalNo="NO-98765432101", Contacter="AndyYou", ContactPhone="0911911911", CreateOn=DateTime.Now, Deleted=false, Event="巨星齊聚苗栗縣元宵節活動", Gym =gyms.Find(x => x.Id == 3), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊" , FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>() },
                new GymRecord{ Id=8, ApprovalNo="NO-98765432102", Contacter="Calvert", ContactPhone="0922922922", CreateOn=DateTime.Now, Deleted=false, Event="霹靂好玩的活動-4", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊" , FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>() },
                new GymRecord{ Id=9, ApprovalNo="NO-98765432101", Contacter="AndyYou", ContactPhone="0911911911", CreateOn=DateTime.Now, Deleted=false, Event="霹靂好玩的活動-5", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊", FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>()  },
                new GymRecord{ Id=10, ApprovalNo="NO-98765432102", Contacter="Calvert", ContactPhone="0922922922", CreateOn=DateTime.Now, Deleted=false, Event="霹靂好玩的活動-6", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊", FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>()  },
                new GymRecord{ Id=11, ApprovalNo="NO-98765432101", Contacter="AndyYou", ContactPhone="0911911911", CreateOn=DateTime.Now, Deleted=false, Event="霹靂好玩的活動-7", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊", FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>()  },
                new GymRecord{ Id=12, ApprovalNo="NO-98765432102", Contacter="Calvert", ContactPhone="0922922922", CreateOn=DateTime.Now, Deleted=false, Event="霹靂好玩的活動-8", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊" , FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>() },
                new GymRecord{ Id=13, ApprovalNo="NO-98765432101", Contacter="AndyYou", ContactPhone="0911911911", CreateOn=DateTime.Now, Deleted=false, Event="霹靂好玩的活動-9", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊", FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>()  },
                new GymRecord{ Id=14, ApprovalNo="NO-98765432102", Contacter="Calvert", ContactPhone="0922922922", CreateOn=DateTime.Now, Deleted=false, Event="霹靂好玩的活動-10", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊", FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>()  },
                new GymRecord{ Id=15, ApprovalNo="NO-98765432101", Contacter="AndyYou", ContactPhone="0911911911", CreateOn=DateTime.Now, Deleted=false, Event="巨星齊聚苗栗縣元宵節活動11", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊", FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>()  },
                new GymRecord{ Id=16, ApprovalNo="NO-98765432102", Contacter="Calvert", ContactPhone="0922922922", CreateOn=DateTime.Now, Deleted=false, Event="春節晚會12", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊" , FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>() },
                new GymRecord{ Id=17, ApprovalNo="NO-98765432101", Contacter="AndyYou", ContactPhone="0911911911", CreateOn=DateTime.Now, Deleted=false, Event="巨星齊聚苗栗縣元宵節活動13", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊", FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>()  },
                new GymRecord{ Id=18, ApprovalNo="NO-98765432102", Contacter="Calvert", ContactPhone="0922922922", CreateOn=DateTime.Now, Deleted=false, Event="春節晚會14", Gym = gyms.FirstOrDefault(), LastEditor="SuperUser", LastUpdateOn=DateTime.Now, LendDateEnd=DateTime.Parse("2013/12/31"), LendDateStart= DateTime.Parse("2013/1/1"), LendUnit="輝網資訊" , FreeItems=new List<FreeItem>(), SendbackItems=new List<SendbackItem>(), PayItems=new List<PayItem>() },

MiaoliGym/Views/GymRecord/Create.cshtml
@model MiaoliGym.Models.GymRecord

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>GymRecord</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.LendUnit)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LendUnit)
            @Html.ValidationMessageFor(model => model.LendUnit)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LendDateStart)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LendDateStart)
            @Html.ValidationMessageFor(model => model.LendDateStart)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LendDateEnd)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LendDateEnd)
            @Html.ValidationMessageFor(model => model.LendDateEnd)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Event)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Event)
            @Html.ValidationMessageFor(model => model.Event)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Contacter)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Contacter)
            @Html.ValidationMessageFor(model => model.Contacter)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ContactPhone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ContactPhone)
            @Html.ValidationMessageFor(model => model.ContactPhone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ApprovalNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ApprovalNo)
            @Html.ValidationMessageFor(model => model.ApprovalNo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CreateOn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreateOn)
            @Html.ValidationMessageFor(model => model.CreateOn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastUpdateOn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastUpdateOn)
            @Html.ValidationMessageFor(model => model.LastUpdateOn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastEditor)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastEditor)
            @Html.ValidationMessageFor(model => model.LastEditor)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Deleted)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Deleted)
            @Html.ValidationMessageFor(model => model.Deleted)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MiaoliGym/Views/GymRecord/Detail.cshtml
@model MiaoliGym.Models.GymRecord
@{
    ViewBag.Title = "館場租借詳細資料";
}
<h4>一般資料</h4>
<div class="container">
    <div class="row">
        <div class="span3">
            @Html.DisplayNameFor(model => model.Gym.Name)
        </div>
        <div class="span6">
            @Html.DisplayFor(model => model.Gym.Name))
        </div>
    </div>
    <div class="row">
        <div class="span3">
            @Html.DisplayNameFor(model => model.Event)
        </div>
        <div class="span6">
            @Html.DisplayFor(model => model.Event)
        </div>
    </div>
    <div class="row">
        <div class="span3">
            @Html.DisplayNameFor(model => model.ApprovalNo)
        </div>
        <div class="span6">
            @Html.DisplayFor(model => model.ApprovalNo)
        </div>
    </div>
    <div class="row">
        <div class="span3">
            @Html.DisplayNameFor(model => model.Contacter)
        </div>
        <div class="span6">
            @Html.DisplayFor(model => model.Contacter)
        </div>
    </div>
    <div class="row">
        <div class="span3">
            @Html.DisplayNameFor(model => model.ContactPhone)
        </div>
        <div class="span6">
            @Html.DisplayFor(model => model.ContactPhone)
        </div>
    </div>
    
    <div class="row">
        <div class="span3">
            @Html.DisplayNameFor(model => model.LendDateStart)
        </div>
        <div class="span6">
            @Html.DisplayFor(model => model.LendDateStart)
        </div>
    </div>
    <div class="row">
        <div class="span3">
            @Html.DisplayNameFor(model => model.LendDateEnd)
        </div>
        <div class="span6">
            @Html.DisplayFor(model => model.LendDateEnd)
        </div>
    </div>
    <div class="row">
        <div class="span3">
            @Html.DisplayNameFor(model => model.LendUnit)
        </div>
        <div class="span6">
            @Html.DisplayFor(model => model.LendUnit)
        </div>
    </div>
</div>


<h4>繳費項目</h4>
<div class="container">
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.PayItems.First().Name)</th>
                <th>@Html.DisplayNameFor(model => model.PayItems.First().PayableDate)</th>
                <th>@Html.DisplayNameFor(model => model.PayItems.First().Price)</th>
                <th>@Html.DisplayNameFor(model => model.PayItems.First().PaidOn)</th>
                <th>@Html.DisplayNameFor(model => model.PayItems.First().IsPaid)</th>
                <th>@Html.DisplayNameFor(model => model.PayItems.First().ReceiptNo)</th>
                @* 用 Helper 調整顯示若無日期則顯示未繳費或未建立 *@
                <th>@Html.DisplayNameFor(model => model.PayItems.First().ReceiptCreateOn)</th>
                <th>@Html.DisplayNameFor(model => model.PayItems.First().ReturnGovOn)</th>  
                <th>@Html.DisplayNameFor(model => model.PayItems.First().Comment)</th>  
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.PayItems)
            { 
                <tr>
                    <td>@Html.DisplayFor(i => item.Name)</td>
                    <td>@Html.DisplayFor(i => item.PayableDate)</td>
                    <td>@Html.DisplayFor(i => item.Price)</td>
                    <td>@Html.DisplayFor(i => item.PaidOn)</td>
                    <td>@Html.DisplayFor(i => item.IsPaid)</td>
                    <td>@Html.DisplayFor(i => item.ReceiptNo)</td>
                    <td>@Html.DisplayFor(i => item.ReceiptCreateOn)</td>
                    <td>@Html.DisplayFor(i => item.ReturnGovOn)</td>
                    <td>@Html.DisplayFor(i => item.Comment)</td>
                </tr>
            }
        </tbody>
    </table>
</div>


<h4>免繳費項目</h4>
<div class="container">
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.FreeItems.First().Name)</th>
                <th>@Html.DisplayNameFor(model => model.FreeItems.First().ApprovalNo)</th>
                <th>@Html.DisplayNameFor(model => model.FreeItems.First().Comment)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.FreeItems)
            { 
                <tr>
                    <td>@Html.DisplayFor(model => item.Name)</td>
                    <td>@Html.DisplayFor(model => item.ApprovalNo)</td>
                    <td>@Html.DisplayFor(model => item.Comment)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<h4>應歸還項目</h4>
<div class="container">
    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.SendbackItems.First().Name)</th>
                <th>@Html.DisplayNameFor(model => model.SendbackItems.First().Price)</th>
                <th>@Html.DisplayNameFor(model => model.SendbackItems.First().ReturnDate)</th>
                <th>@Html.DisplayNameFor(model => model.SendbackItems.First().CheckNo)</th>
                <th>@Html.DisplayNameFor(model => model.SendbackItems.First().Comment)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.SendbackItems)
            { 
                <tr>
                    <td>@Html.DisplayFor(i => item.Name)</td>
                    <td>@Html.DisplayFor(i => item.Price)</td>
                    <td>@Html.DisplayFor(i => item.ReturnDate)</td>
                    <td>@Html.DisplayFor(i => item.CheckNo)</td>
                    <td>@Html.DisplayFor(i => item.Comment)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

MiaoliGym/Views/GymRecord/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IEnumerable<MiaoliGym.Models.GymRecord>

@{
    ViewBag.Title = "館場租用紀錄";
    var data = Model as IPagedList<MiaoliGym.Models.GymRecord>;
}

<form class="form-search">
    @Html.DropDownList("s", ViewData["SearchColumns"] as SelectList, "--請選擇--", new { @class = "span2"})
    <div class="input-append">
        <input type="text" class="span2 search-query">
        <button type="submit" class="btn">搜尋</button>
    </div>
</form>
<table class="table table-condensed table-hover">
    <thead>
       <tr>
           <th>
               @using (Html.BeginForm("Index", "GymRecord", FormMethod.Get, new { id = "SelectedGymId" }))
               {
                   @Html.DropDownList("g", ViewData["Gyms"] as SelectList, "館場名稱", new { @class = "span2"})
               }
           </th>
           <th>@Html.DisplayNameFor(model => model.First().Event)</th>
           <th>@Html.DisplayNameFor(model => model.First().ApprovalNo)</th>
           <th>@Html.DisplayNameFor(model => model.First().LendUnit)</th>
           <th>@Html.DisplayNameFor(model => model.First().Contacter)</th>
           <th>@Html.DisplayNameFor(model => model.First().ContactPhone)</th>
           @{var columnNameDateStart = Html.DisplayNameFor(model => model.First().LendDateStart);}
           <th>@Html.ActionLink(columnNameDateStart.ToString(),"SortStartDate")</th>
           @{var columnNameDateEnd = Html.DisplayNameFor(model => model.First().LendDateEnd);}
           <th>@Html.ActionLink(columnNameDateEnd.ToString(),"SortEndDate")</th>
           @if ((bool)ViewBag.IsManager)
           { 
            <th>@Html.ActionLink("新增", "Create")</th>
           }
       </tr>
    </thead>
    <tbody>
     @if(Model != null)
     {
        foreach (var item in Model)
        { 
            <tr>
            <td>@item.Gym.Name</td>
            <td>@Html.ActionLink(item.Event,"Detail",new {Id = item.Id})</td>
            <td>@item.ApprovalNo</td>
            <td>@item.LendUnit</td>
            <td>@item.Contacter</td>
            <td>@item.ContactPhone</td>
            <td>@item.LendDateStart.ToShortDateString()</td>
            <td>@item.LendDateEnd.ToShortDateString()</td>
            @if ((bool)ViewBag.IsManager)
            { 
                <th>@Html.ActionLink("編輯", "Edit", new { Id = item.Id }, new { style="width:40px;display:inline-block;"})</th>
                <th>@Html.ActionLink("刪除", "Delete", new { Id = item.Id},new { style="width:40px;display:inline-block;"})</th>
            }
            </tr>
        }
     }
    </tbody>
</table>

@Html.PagedListPager(list: data, generatePageUrl: page => Url.Action("Index",new{p = page}))

@section scripts {

<script type="text/javascript">
  $(function() {
      $("#g").change(function () {
          $('#SelectedGymId').submit();
    });
  });
</script>

}