MiaoliGym/Controllers/LendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiaoliGym.Models;

namespace MiaoliGym.Controllers
{
    public class LendController : Controller
    {
        private MiaoliContext db = new MiaoliContext();

        // 器材借用紀錄
        public ActionResult Index()
        {
            return View();
        }

        // 借用項目與詳細資料
        public ActionResult Detail(int id)
        { 
            // TODO: Show LendItem and detail info.
            return View();
        }

        // 新增借用紀錄: 一筆紀錄底下包含很多借用項目
        public ActionResult LendHeaderCreate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LendHeaderCreate(LendHeader header)
        {
            return View();
        }

        // 編輯 借用紀錄
        public ActionResult LendHeaderEdit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult LendHeaderEdit(LendHeader header)
        {
            return View();
        }

        // 刪除 借用紀錄
        [HttpDelete]
        public ActionResult LendHeaderDelete(int id)
        {
            return View();
        }

        //新增 借用項目
        public ActionResult LendItemCreate()
        {
            return View();
        }

        public ActionResult LendItemCreate(LendItem item)
        {
            return View();
        }

        //編輯 借用項目
        public ActionResult LendItemEdit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult LendItemEdit(LendItem item)
        {
            return View();
        }

        // 刪除 借用項目
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // 歸還器材
        public ActionResult SendBack(int id, int amount)
        {
            LendTransaction tr = new LendTransaction(); //交易紀錄
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MiaoliGym/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiaoliGym.Models;
using System.Web.Security;

namespace MiaoliGym.Controllers
{
    public class MemberController : Controller
    {
        private MiaoliContext db = new MiaoliContext(); 

        // 管理員列表
        public ActionResult Index()
        {
            return View();
        }

        // 登入 // TODO: 所有 Controller 都需要權限
        public ActionResult Login(string returnUrl)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string email, string pwd, string returnUrl)
        {
            if (ValidateUser(email, pwd))
            {
                FormsAuthentication.SetAuthCookie(email, false);

                if (String.IsNullOrEmpty(returnUrl))
                {
                    return RedirectToAction("Index", "GymRecord");
                }
                else
                {
                    return Redirect(returnUrl);
                }
            }

            return View();
        }

        private bool ValidateUser(string email, string pwd)
        {
            throw new NotImplementedException();
        }

        // 登出
        public ActionResult Logout()
        {
            // 清除表單驗證的 Cookie
            FormsAuthentication.SignOut();

            Session.Clear();
            return RedirectToAction("Index", "GymRecord");
        }

        // 匯入會員資料
        public ActionResult Import()
        {
            return View();
        }

        // 新增會員
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Member member)
        {
            return View();
        }

        // 編輯 會員
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(Member member)
        {
            return View();
        }
        
        // 移除會員
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MiaoliGym/Controllers/PurchaseRecordController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiaoliGym.Models;

namespace MiaoliGym.Controllers
{
    public class PurchaseRecordController : Controller
    {
        private MiaoliContext db = new MiaoliContext();

        // 首頁-工程採購紀錄
        public ActionResult Index()
        {
            return View(db.PurchaseRecords.ToList());
        }
      
        // 工程採購明細
        public ActionResult Details(int id = 0)
        {
            PurchaseRecord purchaserecord = db.PurchaseRecords.Find(id);
            if (purchaserecord == null)
            {
                return HttpNotFound();
            }
            return View(purchaserecord);
        }

        // 新增 工程採購明細
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(PurchaseRecord purchaserecord)
        {
            if (ModelState.IsValid)
            {
                db.PurchaseRecords.Add(purchaserecord);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(purchaserecord);
        }

        // 編輯 工程採購明細
        public ActionResult Edit(int id = 0)
        {
            PurchaseRecord purchaserecord = db.PurchaseRecords.Find(id);
            if (purchaserecord == null)
            {
                return HttpNotFound();
            }
            return View(purchaserecord);
        }

        [HttpPost]
        public ActionResult Edit(PurchaseRecord purchaserecord)
        {
            if (ModelState.IsValid)
            {
                db.Entry(purchaserecord).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(purchaserecord);
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            PurchaseRecord purchaserecord = db.PurchaseRecords.Find(id);
            db.PurchaseRecords.Remove(purchaserecord);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MiaoliGym/Controllers/SportsStuffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiaoliGym.Models;

namespace MiaoliGym.Controllers
{
    //【庫存】【體育器材】管理
    public class SportsStuffController : Controller
    {
        private MiaoliContext db = new MiaoliContext();

        // 器材列表
        public ActionResult Index()
        {
            return View();
        }

        // 新增器材
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Create(SportsStuff item)
        {
            return View();
        }

        // 編輯器材
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(SportsStuff item)
        {
            return View();
        }

        // 刪除器材
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            return View();
        }


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        
    }
}

MiaoliGym/Views/Shared/_BLayout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="苗栗縣體育場">
    <meta name="author" content="Apputu Co. Ltd.">

    <!-- Le styles -->
    @Styles.Render("~/Content/css")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="~/Content/icons/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/icons/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/icons/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/icons/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/icons/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="@Url.Action("Index","GymRecord")"><strong>苗栗縣體育場</strong></a>
          <div class="nav-collapse">
            <ul class="nav">
              <li>@Html.ActionLink("館場租借","Index","GymRecord")</li>
              <li>@Html.ActionLink("工程採購","Index","PurchaseRecord")</li>
              <li>@Html.ActionLink("器材借用", "Index", "Lend")</li>
              <li>@Html.ActionLink("器材庫存", "Index", "SportsStuff")</li>
              <li>@Html.ActionLink("權限設定", "Index", "Member")</li>     
            </ul>
            @*// TODO: 如果登入顯示登出判斷 *@
            <ul class="nav pull-right">
              <li>@Html.ActionLink("登出", "Logout", "Member")</li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

    @RenderBody()

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)

  </body>
</html>

MiaoliGym/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>